sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start create an image with dockerfile"
  - cd docker-travisCi && docker build -t diddidtjstjs/docker-react-app -f Dockerfile.dev ./

script:
  - docker run -e CI=true diddidtjstjs/docker-react-app npm run test -- --coverage

after_install:
  - echo "Test success"

deploy:
  provider: elasticbeanstalk
  region: 'ap-northeast-2'
  app: 'docker-react-app'
  env: 'Dockerreactapp-env'
  bucket_name: 'elasticbeanstalk-ap-northeast-2-131602538883'
  bucket_path: 'docker-react-app'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
