sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start create an image with dockerfile"
  - cd docker-travisCI && docker build -t diddidtjstjs/docker-react-app -f Dockerfile.dev ./

script:
  - docker run -e CI=true diddidtjstjs/docker-react-app npm run test -- --coverage

after_install:
  - echo "Test success"
